Repository engineerskkw/WinTacToe, pull requests merged in 2019-11, with the labels that each got.

#14 Feature/013 integrate new training platform implementation with gui
  game_app/application.py
  game_app/games/tic_tac_toe/tic_tac_toe_component.py
  tests/training_platform/test.py
  training_platform/clients/monitor_client.py
  training_platform/config.ini
  training_platform/server/common.py
  training_platform/server/environment_server.py
  training_platform/server/service.py
  training_platform/server/stop_server.py
Labels: bug, enhancement

#24 Recover and add new tests to TicTacToeEngine
  environments/tic_tac_toe/tic_tac_toe_engine.py
  environments/tic_tac_toe/tic_tac_toe_engine_utils.py
  tests/environments/test_board.py
  tests/environments/test_tic_tac_toe_engine.py
  tests/environments/test_tic_tac_toe_engine_additional.py
Labels: enhancement, ready for review

#15 Feature/013 integrate new training platform implementation with gui
  game_app/games/tic_tac_toe/tic_tac_toe_component.py
  tests/training_platform/test.py
  training_platform/clients/agent_client.py
  training_platform/clients/monitor_client.py
  training_platform/clients/terminal_human_player/terminal_human_player_client.py
  training_platform/common.py
  training_platform/config.ini
  training_platform/examples/start_monitor_client.py
  training_platform/examples/start_training.py
  training_platform/server/common.py
  training_platform/server/environment_server.py
  training_platform/server/logger.py
  training_platform/server/service.py
  training_platform/server/start_server.py
Labels: bug, enhancement, ready for review

#27 Add restart handling in rl agents
  game_app/games/tic_tac_toe/tic_tac_toe_component.py
  reinforcement_learning/abstract/abstract_agent.py
  reinforcement_learning/agents/basic_mc_agent/basic_mc_agent.py
  training_platform/clients/agent_client.py
  training_platform/server/service.py
Labels: bug, enhancement, ready for review

#13 Feature/009 add q learning agent
  game_app/games/tic_tac_toe/tic_tac_toe_component.py
  reinforcement_learning/abstract/abstract_action_space.py
  reinforcement_learning/abstract/abstract_action_value.py
  reinforcement_learning/abstract/abstract_agent.py
  reinforcement_learning/abstract/abstract_model.py
  reinforcement_learning/abstract/abstract_policy.py
  reinforcement_learning/abstract/abstract_returns.py
  reinforcement_learning/agents/basic_mc_agent/basic_mc_agent.py
  reinforcement_learning/agents/common/action_value_derived_policy.py
  reinforcement_learning/agents/common/agent_utils.py
  reinforcement_learning/agents/common/lazy_tabular_action_value.py
  reinforcement_learning/agents/q_learning_agent/q_learning_agent.py
  training_platform/clients/agent_client.py
  training_platform/clients/terminal_human_player/terminal_human_player_client.py
  training_platform/examples/create_agents.py
  training_platform/examples/start_training.py
  training_platform/server/common.py
  training_platform/server/environment_server.py
  training_platform/server/service.py
Labels: enhancement, ready for review

#12 Add Base Engine
  environments/base/base_engine.py
  environments/tic_tac_toe/tic_tac_toe_engine.py
  tests/environments/test_tic_tac_toe_engine.py
  tests/environments/test_tic_tac_toe_engine_additional.py
  training_platform/server/service.py
Labels: enhancement, ready for review, refactoring

#35 Refactor abstract to base everywhere
  environments/base/base_engine.py
  environments/tic_tac_toe/tic_tac_toe_engine_utils.py
  reinforcement_learning/abstract/abstract_state_value.py
  reinforcement_learning/agents/basic_mc_agent/basic_mc_agent.py
  reinforcement_learning/agents/basic_mc_agent/episode.py
  reinforcement_learning/agents/basic_mc_agent/simple_action.py
  reinforcement_learning/agents/basic_mc_agent/simple_state.py
  reinforcement_learning/agents/common/action_value_derived_policy.py
  reinforcement_learning/agents/common/lazy_tabular_action_value.py
  reinforcement_learning/base/base_action.py
  reinforcement_learning/base/base_action_space.py
  reinforcement_learning/base/base_action_value.py
  reinforcement_learning/base/base_agent.py
  reinforcement_learning/base/base_model.py
  reinforcement_learning/base/base_policy.py
  reinforcement_learning/base/base_returns.py
  reinforcement_learning/base/base_state.py
  training_platform/clients/terminal_human_player/terminal_human_player_agent.py
  training_platform/examples/create_agents.py
  training_platform/examples/distributed_initialization/start_agent_client_0.py
  training_platform/examples/distributed_initialization/start_agent_client_1.py
  training_platform/examples/start_training.py
  training_platform/server/service.py
Labels: refactoring

#37 Add Base player and winning
  environments/base/base_engine.py
  environments/base/base_engine_utils.py
  environments/tic_tac_toe/tic_tac_toe_engine_utils.py
Labels: ready for review, refactoring

#43 Simplify training process
  Pipfile
  reinforcement_learning/agents/q_learning_agent/q_learning_agent.py
  reinforcement_learning/common/simple_training.py
  reinforcement_learning/common/start_training.py
  training_platform/examples/start_training.py
Labels: RL, enhancement

#50 Add exit button to main menu
  game_app/application.py
  game_app/games/tic_tac_toe/tic_tac_toe_component.py
  game_app/menus/main_menu/main_menu_logic.py
  game_app/menus/settings/settings_logic.py
  game_app/resources/images/settings/reset_icon_black.png
  game_app/resources/images/settings/reset_icon_white.png
  game_app/resources/images/settings/save_icon_black.png
  game_app/resources/images/settings/save_icon_white.png
Labels: GUI, enhancement, ready for review

#49 Add N-step agent
  environments/tic_tac_toe/tic_tac_toe_engine.py
  reinforcement_learning/agents/common/agent_utils.py
  reinforcement_learning/agents/n_step_agent/n_step_agent.py
  reinforcement_learning/agents/q_learning_agent/q_learning_agent.py
  reinforcement_learning/common/create_agents.py
  reinforcement_learning/common/start_training.py
Labels: RL, enhancement, ready for review

#54 Add random agent
  environments/base/base_engine.py
  environments/base/base_engine_utils.py
  environments/tic_tac_toe/gather_winnings_strategies.py
  environments/tic_tac_toe/tic_tac_toe_engine.py
  environments/tic_tac_toe/tic_tac_toe_engine_utils.py
  reinforcement_learning/agents/common/lazy_tabular_action_value.py
  reinforcement_learning/agents/n_step_agent/n_step_agent.py
  reinforcement_learning/agents/q_learning_agent/q_learning_agent.py
  reinforcement_learning/agents/random_agent/random_agent.py
  reinforcement_learning/base/base_agent.py
  reinforcement_learning/common/create_agents.py
  reinforcement_learning/common/simple_training.py
  reinforcement_learning/common/start_training.py
Labels: RL, enhancement, ready for review

#52 Fix agent policies and action value funtions
  environments/tic_tac_toe/tic_tac_toe_engine.py
  environments/tic_tac_toe/tic_tac_toe_engine_utils.py
  reinforcement_learning/agents/basic_mc_agent/episode.py
  reinforcement_learning/agents/basic_mc_agent/returns.py
  reinforcement_learning/agents/basic_mc_agent/stochastic_model.py
  reinforcement_learning/agents/basic_mc_agent/training.py
  reinforcement_learning/agents/common/action_value_derived_policy.py
  reinforcement_learning/agents/common/lazy_tabular_action_value.py
  reinforcement_learning/agents/q_learning_agent/q_learning_agent.py
  reinforcement_learning/base/base_action_value.py
  reinforcement_learning/common/start_training.py
  tests/mock/mock_action.py
  tests/mock/mock_action_space.py
  tests/mock/mock_state.py
  tests/reinforcement_learning/test.py
  tests/reinforcement_learning/test_actionValueDerivedPolicy.py
  tests/reinforcement_learning/test_lazyTabularActionValue.py
Labels: RL, bug, ready for review, refactoring
